/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.umstek.biometrics.keystrokedynamics;

import javax.swing.JOptionPane;
import lk.umstek.biometrics.keystrokedynamics.features.FeatureExtractor;
import lk.umstek.biometrics.keystrokedynamics.features.FeatureMatcher;
import lk.umstek.biometrics.keystrokedynamics.features.FeatureModel;
import lk.umstek.biometrics.keystrokedynamics.input.EventCollector;
import lk.umstek.biometrics.keystrokedynamics.persistence.FileIO;

/**
 *
 * @author wickramaranga
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelInfo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextRef = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAct = new javax.swing.JTextArea();
        jButtonNext = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelInfo.setText("Please type the following text to login. Type everything in lowercase. ");

        jTextRef.setEditable(false);
        jTextRef.setColumns(20);
        jTextRef.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextRef.setLineWrap(true);
        jTextRef.setRows(5);
        jTextRef.setText("the behavioral biometric of keystroke dynamics uses the manner and rhythm in which an individual types characters on a keyboard or keypad. the keystroke rhythms of a user are measured to develop a unique biometric template of the user's typing pattern for future authentication.");
        jTextRef.setWrapStyleWord(true);
        jTextRef.setEnabled(false);
        jScrollPane1.setViewportView(jTextRef);

        jTextAct.setColumns(20);
        jTextAct.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextAct.setLineWrap(true);
        jTextAct.setRows(5);
        jTextAct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextActKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextActKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTextAct);

        jButtonNext.setText("Login");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelInfo)
                        .addGap(0, 201, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonReset)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonNext)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelInfo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNext)
                    .addComponent(jButtonReset))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    EventCollector collector = new EventCollector();

    private void jTextActKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextActKeyPressed
        collector.press(evt, false);
    }//GEN-LAST:event_jTextActKeyPressed

    private void jTextActKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextActKeyReleased
        collector.release(evt, false);
    }//GEN-LAST:event_jTextActKeyReleased

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        jTextAct.setText("");
        collector = new EventCollector();
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        if (jTextRef.getText().equals(jTextAct.getText())) {
            FeatureModel model = FeatureExtractor.extractFeatures(collector);
            FeatureModel ref = FileIO.loadModel();

            if (FeatureMatcher.match(model, ref)) {
                JOptionPane.showMessageDialog(this, "Login successful. ");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Login error. ", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Please enter the correct text. ");
        }
    }//GEN-LAST:event_jButtonNextActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAct;
    private javax.swing.JTextArea jTextRef;
    // End of variables declaration//GEN-END:variables
}
